package net.rationalstargazer.events.lifecycle

typealias CoroutineLifecycle = RStaCoroutineLifecycle
typealias LifecycleBasedCoroutineDispatcher = RStaLifecycleBasedCoroutineDispatcher
typealias LifecycleBasedSimpleCoroutineDispatcher = RStaLifecycleBasedSimpleCoroutineDispatcher